### PR TITLE
Add Dynamic Where Clause and firstOrCreate() tips

### PR DESCRIPTION
**Pull request by mnurullahsaglam**
I've added dynamic where clause and using firstOrCreate() in DB Models and Eloquent.

If this PR merges, the tip count in DB Models and Eloquent will reach 100 tips!

### CODE REVIEW

**Comment by krekas** [comment]
Personally wouldn't recommend using `Dynamic Where Clauses`

**Comment by mnurullahsaglam** [comment]
I find dynamic where clauses very handy and readable

**Comment by PovilasKorop** [comment]
@mnurullahsaglam I agree with @krekas on this, but maybe some people prefer this option so it may be ok to show options as quick tips. Ok, merging both, thanks for contributing!

**Comment by mnurullahsaglam** [comment]
Respect both of you. Thank you for merging

**Pull request merged**
