### PR TITLE
Update Other.md

### PR DESCRIPTION
**Pull request by ramay2088**
Add Two tips 

1- Run jobs in sequence
2- Perform action when job is failed

### CODE REVIEW

**Comment by PovilasKorop** [comment]
@ramay2088 thank you for your PR! It contains a lot of formatting unrelated to the topic, so it's very inconvenient to review: 
Screenshot 2022-08-01 at 07 02 52

Please remove the formatting changes and then I could actually read your suggested tips conveniently, and merge.

**Comment by ramay2088** [comment]
Sorry for the mistake it was my second contribution to someone else's repo I made mistake. can you please have a look I tried to fix it? If it doesn't work I can create new PR

**Comment by ramay2088** [comment]
By the way big fan of you sir @PovilasKorop

**Comment by PovilasKorop** [comment]
@ramay2088 thanks, better now, merged.

Next time please check the grammar and code styling, cause this repo will be read by thousands of people, so needs to be polished: https://github.com/LaravelDaily/laravel-tips/commit/599e00728a6022300d8b9a26b2529e8ac320f6c6

**Pull request merged**
