### PR TITLE
Controller groups with name route and url

### PR DESCRIPTION
**Pull request by bdj-Razik**

### CODE REVIEW

**Comment by PovilasKorop** [comment]
@bdj-Razik pretty sure it's the same tip as existing one: https://github.com/LaravelDaily/laravel-tips/blob/master/routing.md#controller-groups

Or am I missing something?

**Comment by bdj-Razik** [comment]
Yes sure , you can compare them
because there is no shortcuts to URLs with route name. I added préfixe URL with route name

**Comment by PovilasKorop** [comment]
@bdj-Razik sorry but I don't think that prefix and route name can be useful as a separate tip.

**Comment by bdj-Razik** [comment]
The one I added is more organized than before because i added préfixe for URL and route name

**Pull request closed without merging**
