### PR TITLE
Simple routing with arrow function PHP.

### PR DESCRIPTION
**Pull request by novalramdhani**
(+) add new tips!

### CODE REVIEW

**Comment by chengkangzai** [comment]
IMO view might not be the best way to demo this feature since it can be replaced with 
```php 
Route::view('dashboard', 'dashboard');
```

If this PR be accepted, I would suggest returning some objects like this for better clarity 
```php
//before 
Route::get('test',function (){
    return User::find(1);
});

//after
Route::get('test', fn() => User::find(1));
```

Happy New Year btw ✨

**Comment by novalramdhani** [comment]
> IMO view might not be the best way to demo this feature since it can be replaced with
> 
> ```
> Route::view('dashboard', 'dashboard');
> ```
> 
> If this PR be accepted, I would suggest returning some objects like this for better clarity
> 
> ```
> //before 
> Route::get('test',function (){
>     return User::find(1);
> });
> 
> //after
> Route::get('test', fn() => User::find(1));
> ```
> 
> Happy New Year btw ✨

yeah. Good suggestion, i will change it. Thank you.

**Comment by chengkangzai** [comment]
btw you missing the hash value [here](https://github.com/LaravelDaily/laravel-tips/pull/54/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R2055)

**Comment by novalramdhani** [comment]
> btw you missing the hash value [here](https://github.com/LaravelDaily/laravel-tips/pull/54/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R2055)

done!

**Comment by PovilasKorop** [comment]
@novalramdhani thanks for the tip! I've merged it, but I guess this tip is not that much about routing, but rather about short functions syntax. So not sure if the routing is the best example, as I've never really done such one-liner function in routs, from what I remember. But maybe someone else will find it useful, so leaving it merged, thanks again!

**Comment by novalramdhani** [comment]
> @novalramdhani thanks for the tip! I've merged it, but I guess this tip is not that much about routing, but rather about short functions syntax. So not sure if the routing is the best example, as I've never really done such one-liner function in routs, from what I remember. But maybe someone else will find it useful, so leaving it merged, thanks again!

thank you @PovilasKorop.

**Pull request merged**
